""" Script generated by ansys-mapdl-core version 0.57.5 """
import os
from ansys.mapdl.core import launch_mapdl
import matplotlib as plt

path = os.getcwd() + '//engine//linearAnalysi//ansysData'
 
mapdl = launch_mapdl(run_location=path, loglevel="INFO")

# ##############  ANALISE ESTRUTURAL DE VIGA I - FB6  ##############

# =======  CONFIGURACOES INICIAIS  =======
# help(mapdl.post_processing)
mapdl.finish()

mapdl.run("/CLEAR,START")

mapdl.run("/FILNAME,VigaI-FB6,0")

# =======  DECLARACAO DAS VARIAVEIS  =======

# 1 - Geometria:

mapdl.run("t=0.00635")

mapdl.run("bf=0.1524")

mapdl.run("d=0.1524")

mapdl.run("bw=d-t")

# L=2.9

# L=2.6

# L=2.2

mapdl.run("L=1.8")

# Lshear=1

# Lshear=0.9

# Lshear=0.8

mapdl.run("Lshear=0.7")

# 2 - Propriedades do material:

# Propriedades informadas pela fabricante

# Ex=5500000000

# Ey=5500000000

# Ez=17200000000

# PRxy=0.16

# PRyz=0.16

# PRxz=0.32

# Gxy=3100000000

# Gyz=3100000000

# Gxz=3100000000

# Dens=1800

# Propriedades informadas pela ASCE

mapdl.run("Ex=5516000000")

mapdl.run("Ey=5516000000")

mapdl.run("Ez=20685000000")

mapdl.run("PRxy=0.16")

mapdl.run("PRyz=0.16")

mapdl.run("PRxz=0.32")

mapdl.run("Gxy=2758000000")

mapdl.run("Gyz=2758000000")

mapdl.run("Gxz=2758000000")

mapdl.run("Dens=1800")

# =======  PRE-PROCESSAMENTO  =======

# -------  INICIALIZACAO DA FASE DE PRE-PROCESSAMENTO  -------

mapdl.run("/PREP7")

mapdl.run("/VIEW,1,1,1,1")

mapdl.run("/TITLE,Viga I - Secao: %d*1000% x %bf*1000% - Comprimento: %L%m")

mapdl.run("/REPLOT")

# BCSOPTION,,DEFAULT

# -------  CRIACAO DO ELEMENTO FINITO  -------

mapdl.et(1, "SHELL181")

mapdl.keyopt(1, 1, 0)  #Element stiffness: 0 - Bending and membrane stiffness (default)

mapdl.keyopt(1, 3, 2)  #Integration option: 2 - Full integration with incompatible modes

mapdl.keyopt(1, 8, 0)  #Specify layer data storage: 0 - Store data for bottom of bottom layer and top of top layer (multi-layer elements) (default)

mapdl.keyopt(1, 9, 0)  #User thickness option: 0 - No user subroutine to provide initial thickness (default)

mapdl.keyopt(1, 10, 0)  #Curved shell formulation: 0 - Standard shell formulation (default)

# -------  CRIACAO DO MATERIAL  -------

mapdl.mp("EX", 1, "Ex")

mapdl.mp("EY", 1, "Ey")

mapdl.mp("EZ", 1, "Ez")

mapdl.mp("PRXY", 1, "PRxy")

mapdl.mp("PRXZ", 1, "PRxz")

mapdl.mp("PRYZ", 1, "PRyz")

mapdl.mp("GXY", 1, "Gxy")

mapdl.mp("GXZ", 1, "Gxz")

mapdl.mp("GYZ", 1, "Gyz")

mapdl.mp("DENS", 1, "Dens")

# -------  CRIACAO DA SECAO  -------

mapdl.sectype(1, "SHELL", "", "perfil")

mapdl.secoffset("MID")

mapdl.secdata("t", 1)

# -------  LOCACAO DOS KEYPOINTS  -------

mapdl.k(1, 0, 0, 0)

mapdl.k(2, "bf/2", 0, 0)

mapdl.k(3, "bf", 0, 0)

mapdl.k(4, 0, "bw", 0)

mapdl.k(5, "bf/2", "bw", 0)

mapdl.k(6, "bf", "bw", 0)

mapdl.k(101, 0, 0, "Lshear")

mapdl.k(102, "bf/2", 0, "Lshear")

mapdl.k(103, "bf", 0, "Lshear")

mapdl.k(104, 0, "bw", "Lshear")

mapdl.k(105, "bf/2", "bw", "Lshear")

mapdl.k(106, "bf", "bw", "Lshear")

mapdl.k(201, 0, 0, "L-Lshear")

mapdl.k(202, "bf/2", 0, "L-Lshear")

mapdl.k(203, "bf", 0, "L-Lshear")

mapdl.k(204, 0, "bw", "L-Lshear")

mapdl.k(205, "bf/2", "bw", "L-Lshear")

mapdl.k(206, "bf", "bw", "L-Lshear")

mapdl.k(301, 0, 0, "L")

mapdl.k(302, "bf/2", 0, "L")

mapdl.k(303, "bf", 0, "L")

mapdl.k(304, 0, "bw", "L")

mapdl.k(305, "bf/2", "bw", "L")

mapdl.k(306, "bf", "bw", "L")

# -------  CRIACAO DAS AREAS  -------

mapdl.a(1, 2, 102, 101)

mapdl.a(2, 3, 103, 102)

mapdl.a(4, 5, 105, 104)

mapdl.a(5, 6, 106, 105)

mapdl.a(2, 5, 105, 102)

mapdl.a(101, 102, 202, 201)

mapdl.a(102, 103, 203, 202)

mapdl.a(104, 105, 205, 204)

mapdl.a(105, 106, 206, 205)

mapdl.a(102, 105, 205, 202)

mapdl.a(201, 202, 302, 301)

mapdl.a(202, 203, 303, 302)

mapdl.a(204, 205, 305, 304)

mapdl.a(205, 206, 306, 305)

mapdl.a(202, 205, 305, 302)

# -------  GERACAO DE ELEMENTO E MALHA  -------

mapdl.asel("ALL")

mapdl.aatt(1, 1, 1, 0, 1)

mapdl.mshkey(1)

mapdl.aesize("ALL", 0.01)

mapdl.amesh("ALL")

# -------  FINALIZACAO DA FASE DE PRE-PROCESSAMENTO -------

mapdl.finish()

# =======  PROCESSAMENTO  =======

# -------  INICIALIZACAO DA FASE DE PROCESSAMENTO  -------

mapdl.run("/SOLU")

# -------  DEFINICAO DAS RESTRICOES DE GRAU DE LIBERDADE  -------

mapdl.nsel("S", "LOC", "Z", 0)

mapdl.nsel("R", "LOC", "X", 0, "bf")

mapdl.nsel("R", "LOC", "Y", 0)

mapdl.d("ALL", "UX", 0)

mapdl.d("ALL", "UY", 0)

mapdl.d("ALL", "UZ", 0)

mapdl.nsel("S", "LOC", "Z", "L")

mapdl.nsel("R", "LOC", "X", 0, "bf")

mapdl.nsel("R", "LOC", "Y", 0)

mapdl.d("ALL", "UX", 0)

mapdl.d("ALL", "UY", 0)

mapdl.nsel("S", "LOC", "Z", 0)

mapdl.nsel("R", "LOC", "X", 0, "bf")

mapdl.nsel("R", "LOC", "Y", "bw")

mapdl.d("ALL", "UX", 0)

mapdl.d("ALL", "ROTZ", 0)

mapdl.nsel("S", "LOC", "Z", "L")

mapdl.nsel("R", "LOC", "X", 0, "bf")

mapdl.nsel("R", "LOC", "Y", "bw")

mapdl.d("ALL", "UX", 0)

mapdl.d("ALL", "ROTZ", 0)

# NSEL,NONE

# -------  DEFINICAO DO CARREGAMENTO  -------

mapdl.fk(105, "FY", -1)

mapdl.fk(205, "FY", -1)

# -------  ANALISE ESTATICA  -------

mapdl.antype("STATIC")

mapdl.pstres("ON")

mapdl.allsel("ALL")

mapdl.solve()

mapdl.finish()

# -------  ANALISE DE ESTABILIDADE ELASTICA (FLAMBAGEM)  -------

mapdl.run("/SOLU")

mapdl.antype("BUCKLE")

mapdl.bucopt("LANB", 10)

mapdl.solve()

mapdl.finish()

# ------- ESPORTAR AS IMAGENS -------

mapdl.aplot(vtk=False)

mapdl.post_processing

mapdl.post_processing.run("SUBSET,1,5")  #MODO 5 DE FLAMBAGEM

# mapdl.post_processing.plot_nodal_displacement('NORM', smooth_shading=True, off_screen=True, screenshot=True)

mapdl.run("PLNSOL,U,SUM")

mapdl.run("/REPLOT")  # Automatically reissues the last display command for convenience.

mapdl.run("/SHOW,JPEG,,0")  # Specifies the device and other parameters for graphics displays

mapdl.jpeg("QUAL",100)  #Provides JPEG file export for ANSYS displays

mapdl.jpeg("ORIENT", "HORIZ")  #'

mapdl.jpeg("COLOR", 2)  #'

mapdl.jpeg("TMOD", 1)  #'

mapdl.run("/GFILE,800")  # Specifies the pixel resolution on Z-buffered graphics files

mapdl.run("/REPLOT")  # Automatically reissues the last display command for convenience.

mapdl.run("/SHOW,CLOSE")  # Specifies the device and other parameters for graphics displays

mapdl.run("/DEVICE,VECTOR,0")  # Controls graphics device options

mapdl.exit()

